# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=30)),
                ('valorCompra', models.IntegerField(default=0)),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('kilometraje', models.IntegerField(default=0)),
                ('electrico', models.IntegerField(default=0)),
                ('mecanico', models.IntegerField(default=0)),
                ('llantas', models.IntegerField(default=0)),
                ('accesorios', models.IntegerField(default=0)),
                ('detallado', models.IntegerField(default=0)),
                ('extras', models.IntegerField(default=0)),
                ('depreciacion', models.IntegerField(default=0)),
                ('costoMantenimiento', models.IntegerField(default=0)),
                ('subTotal', models.IntegerField(default=0)),
                ('valorVenta', models.IntegerField(default=0)),
                ('fechaVenta', models.DateTimeField(blank=True)),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
    ]
