# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socrates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fechaVenta',
        ),
    ]
